# Generated by Django 3.1 on 2020-09-06 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete',
            name='data_publicacao',
            field=models.DateField(default=datetime.date(2020, 9, 6)),
        ),
    ]
