# Generated by Django 3.1 on 2020-09-06 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0002_auto_20200906_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete',
            name='data_publicacao',
            field=models.DateField(default=datetime.date(2020, 9, 5)),
        ),
    ]
