# Generated by Django 3.1 on 2020-09-06 02:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0003_auto_20200905_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete',
            name='data_publicacao',
            field=models.DateField(default=datetime.datetime(2020, 9, 6, 2, 14, 10, 533460, tzinfo=utc)),
        ),
    ]
