# Generated by Django 3.1 on 2020-09-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0004_auto_20200905_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete',
            name='data_publicacao',
            field=models.DateField(),
        ),
    ]
